FROM node:20.8-alpine3.18 as build-stage
WORKDIR /app
COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN yarn install
COPY ./frontend ./
RUN yarn build

# Production stage
FROM nginx:1.25.2-alpine3.18 as production-stage

# Copy nginx configuration and files
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./frontend/nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 82
CMD ["nginx", "-g", "daemon off;"]